// Characters types
export const FETCH_CHARACTERS = 'FETCH_CHARACTERS';
export const PENDING_CHARACTERS = 'PENDING_CHARACTERS';
export const REJECT_CHARACTERS = 'REJECT_CHARACTERS';
export const FETCH_SINGLE_CHARACTER = 'FETCH_SINGLE_CHARACTER';
export const PENDING_SINGLE_CHARACTER = 'PENDING_SINGLE_CHARACTER';
export const REJECT_SINGLE_CHARACTER = 'REJECT_SINGLE_CHARACTER';
export const RESET_DATA = 'RESET_DATA';
export const CHANGE_PARAMS = 'CHANGE_PARAMS';
export const LOAD_MORE_DATA = 'LOAD_MORE_DATA';

// Episodes types
export const PENDING_EPISODES = 'PENDING_EPISODES';
export const FETCH_EPISODES = 'FETCH_EPISODES';
export const REJECT_EPISODES = 'REJECT_EPISODES';
export const PENDING_SINGLE_EPISODE = 'PENDING_SINGLE_EPISODE';
export const FETCH_SINGLE_EPISODE = 'FETCH_SINGLE_EPISODE';
export const REJECT_SINGLE_EPISODE = 'REJECT_SINGLE_EPISODE';
export const RESET_DATA_EPISODES = 'RESET_DATA_EPISODES';
